name: NewsBridge
channels:
  - defaults
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2025.2.25
  - libffi=3.4.4
  - ncurses=6.4
  - openssl=3.0.16
  - pip=25.1
  - python=3.11.11
  - readline=8.2
  - setuptools=78.1.1
  - sqlite=3.45.3
  - tk=8.6.14
  - tzdata=2025b
  - wheel=0.45.1
  - xz=5.6.4
  - zlib=1.2.13
  - pip:
      - blinker==1.9.0
      - cachetools==5.5.2
      - certifi==2025.4.26
      - charset-normalizer==3.4.2
      - click==8.2.0
      - dotenv==0.9.9
      - flask==3.1.1
      - flask-cors==5.0.1
      - google-auth==2.40.1
      - google-auth-oauthlib==1.2.2
      - gspread==6.2.0
      - httplib2==0.22.0
      - idna==3.10
      - itsdangerous==2.2.0
      - jinja2==3.1.6
      - markupsafe==3.0.2
      - oauth2client==4.1.3
      - oauthlib==3.2.2
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pyparsing==3.2.3
      - python-dotenv==1.1.0
      - requests==2.32.3
      - requests-oauthlib==2.0.0
      - rsa==4.9.1
      - six==1.17.0
      - urllib3==2.4.0
      - werkzeug==3.1.3
